export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const REPOSITORY = {
  USER: 'USER_REPOSITORY',
  PRODUCT: 'PRODUCT_REPOSITORY',
  LOG: 'LOG_REPOSITORY',
  ACTIVITY: 'ACTIVITY_REPOSITORY',
  ORDER: 'ORDER_REPOSITORY',
  PAYMENT: 'PAYMENT_REPOSITORY',
  DELIVERY: 'DELIVERY_REPOSITORY',
  COUPON: 'COUPON_REPOSITORY',
  WISHLIST: 'WISHLIST_REPOSITORY',
  REVIEW: 'REVIEW_REPOSITORY',
  CART: 'CART_REPOSITORY',
  CART_ITEM: 'CART_ITEM_REPOSITORY',
  CATEGORY: 'CATEGORY_REPOSITORY',
  WEBHOOK_EVENT: 'WEBHOOK_EVENT_REPOSITORY',
};
